spring.application.name=EMS

jwt.secret=9f4b7c2e8a1d5f6c3b8e7a2d1c9f5e6b7a3d8c1f2e4b6a9d7c5e1f8b3a6d2c4


# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# MYSQL DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/EMS?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Apr@2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# OPTIONAL LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
